### ISSUE TITLE
AttributeError: module 'typing' has no attribute 'TupleMeta'

### ISSUE THREAD

**Issue by paolodm** [bannsec/gallimaufry#8]
Getting this after `pip3 install .`:

```

Python 3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from Gallimaufry.USB import USB
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/paolodm/code/gallimaufry/Gallimaufry/__init__.py", line 2, in <module>
    from .USB import USB
  File "/Users/paolodm/code/gallimaufry/Gallimaufry/USB.py", line 5, in <module>
    import enforce
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/enforce-0.3.4-py3.7.egg/enforce/__init__.py", line 1, in <module>
    from .decorators import runtime_validation
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/enforce-0.3.4-py3.7.egg/enforce/decorators.py", line 11, in <module>
    from .enforcers import apply_enforcer, Parameters, GenericProxy
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/enforce-0.3.4-py3.7.egg/enforce/enforcers.py", line 10, in <module>
    from .validator import init_validator, Validator
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/enforce-0.3.4-py3.7.egg/enforce/validator.py", line 4, in <module>
    from .parsers import get_parser
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/enforce-0.3.4-py3.7.egg/enforce/parsers.py", line 225, in <module>
    typing.TupleMeta: _parse_tuple,
AttributeError: module 'typing' has no attribute 'TupleMeta'
```

**Comment by bannsec** [comment]
Could you try just commenting out "import enforce" and the related enforce
decorators? Guessing that would fix it.

**Comment by paolodm** [comment]
Thanks. That does work. 

For future viewers, [root cause](https://github.com/RussBaz/enforce/issues/71) was due to enforce not supporting python3.7. I suppose downgrading to an older version would have worked here as well.

**Comment by bannsec** [comment]
I'm just gonna remove it. It's been more trouble than it's worth.
